name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '10'
        cache: 'npm'
    - run: npm install

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Deploy to BunnyCDN
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/website/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
